name: Run Replit Script

on:
  schedule:
    # every 6 hours at minute 0 UTC (which hits approximately 00:30, 06:30, 12:30, 18:30 IST)
    - cron: '0 0,6,12,18 * * *'

jobs:
  run-replit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install playwright
      - run: node run-replit.js
        env:
          REPL_EMAIL: ${{ secrets.REPL_EMAIL }}
          REPL_PASSWORD: ${{ secrets.REPL_PASSWORD }}
          REPL_URL: ${{ secrets.REPL_URL }}
